import React, { ReactNode } from "react";
import Nav from "./Nav";
import Head from "next/head";

type Props = {
  children: ReactNode;
};

function MainLayout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Honey Badgers Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Nav />
        {children}
        <div>Footer</div>
      </div>
    </>
  );
}

export default MainLayout;
